version: '3.8'

services:
  php:
    build:
      context: .
      dockerfile: Dockerfile.php
    volumes:
      - ./public-html:/var/www/html
    networks:
      - app-network

  apache:
    image: httpd:2.4-alpine
    depends_on:
      - php
    ports:
      - "8080:80"
    volumes:
      - ./public-html:/usr/local/apache2/htdocs/
    networks:
      - app-network

  mariadb:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: mydatabase
      MYSQL_USER: myuser
      MYSQL_PASSWORD: mypassword
    volumes:
      - db_data:/var/lib/mysql
    ports:
      - "3307:3306"
    networks:
      - app-network

networks:
  app-network:
    driver: bridge

volumes:
  db_data:
