# Utiliser Alpine Linux comme base
FROM alpine:latest

# Installer MariaDB
RUN apk add --no-cache mariadb mariadb-client

# Copier les scripts de configuration ou les fichiers nécessaires
# Exemple : COPY ./my-custom.cnf /etc/mysql/mariadb.cnf

# Exposer le port 3306
EXPOSE 3306

# Commande pour démarrer le serveur MariaDB
CMD ["mysqld_safe"]
